name: Build Flatpak

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Build and upload Flatpak
        env:
          APPID: "moe.nyarchlinux.assistant"
          BUNDLENAME: "nyarchassistant.flatpak"
        run: |
          flatpak-builder --install --user --force-clean flatpak-app "$APPID".json
          flatpak build-bundle ~/.local/share/flatpak/repo "$BUNDLENAME" "$APPID"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nyarchassistant.flatpak
          path: nyarchassistant.flatpak
